- docs/modules/README.md
- docs/modules/cpx.md
Add replacement for `cpx`, similar to what I did in https://github.com/renovatebot/renovate/pull/27507. Closes https://github.com/es-tooling/module-replacements/issues/18.
> feat: add replacement for cpx

- docs/modules/tempy.md
- manifests/preferred.json
Not sure what Node version to put this at. `fs.mkdtemp` itself goes back to Node v5, but `fs.rmdir(..., {recursive: true}` is Node 12.x and up, and it now gives you a big deprecation message telling you to use `fs.rm` instead, which is Node 14.x and up.
It shouldn't be too much of a problem, however, since `tempy` is also Node 14.x and up.
> feat: add replacement for tempy

- manifests/native.json
From `es-shims` project, in addition to already added, without adding polyfills for modern features that are required for recent engines. They are too bloated and have tenths of dependencies that unfold to hundreds of subdependencies. The situation is similar to the situation by the link from https://github.com/es-tooling/module-replacements/pull/38.
> Add some too bloated `Array` polyfills

- manifests/native.json
Resume #39
Without adding polyfills for recent features.
I'm not sure where should be added https://github.com/es-shims/es-string-html-methods since it contains polyfills for some features and breaks the `native` schema.
> Add some too bloated `String` polyfills

- docs/modules/eslint-plugin-react.md
The author is on the Discord and recommended against using it there. It had only a single release nine months ago and he's moved onto other things
> docs: remove recommendation for shimful plugin

- docs/modules/mkdirp.md
- docs/modules/rimraf.md
- manifests/preferred.json
- package-lock.json
- package.json
These packages' functionality have been integrated into Node's `fs` module, and can usually be removed.
> feat: replacements for mkdirp and rimraf

- docs/modules/qs.md
A lot of projects have heavy reliance on qs and their specific way of handling nested objects/arrays. It's also undeniable that their code has been battle-tested and is secure.
Thus, I forked it and got rid of all the bad parts of `qs`. While, personally, I would switch new projects to `picoquery` - the only package with nested arrays & objects support - it's
- much more effort to migrate existing projects to it
- a hard sell for larger projects, especially within companies, as it's a very recent package and is not as battle-tested as `qs`
- lacking some configuration options available in `qs`
> docs: add qs-esm as an alternative to qs

- docs/modules/README.md
- docs/modules/jquery.md
- manifests/preferred.json
> Add `jQuery`

- docs/modules/README.md
- docs/modules/uri-js.md
- manifests/preferred.json
s/o @valadaptive - thanks for the research!
resolves https://github.com/43081j/ecosystem-cleanup/issues/60
Adds entry for `uri-js` library and recommends two alternatives, `uri-js-replace` (identical API) and `fast-uri` (different API but faster)
> feat: Add entry for uri-js

- docs/modules/README.md
- docs/modules/mkdirp.md
- docs/modules/readable-stream.md
- manifests/native.json
- manifests/preferred.json
* `make-dir` ( Fixes #62 ) ( Fixes #37 is already fixed )
* `object.keys` with `Object.keys` (this is identical to the `object-keys` package
* `object-assign` with `Object.assign` (this is identical to the `object.assign` package
* `readable-stream` that can be replaced by `node:stream`
> Add more replacements: make-dir, object-keys, object-assign, readable-stream

- manifests/native.json
Correct module name is `string.prototype.trimstart` but there was `trimStart` before.
See https://www.npmjs.com/package/string.prototype.trimstart
> fix: fix module name casing

- manifests/micro-utilities.json
Change `is-primitve` to `is-primitive` to match spelling of the npm package.
> bugfix: fix the naming of `is-primitive`

- manifests/native.json
[Source](https://github.com/es-shims/Number.prototype.toExponential/blob/776e7261fdaf14bddee9cd822daa4bb9914ecc4b/package.json#L2)
[npmjs.com](https://www.npmjs.com/package/number.prototype.toexponential)
There's typo in his package `README.md`.
> fix: typo in package name `exponential` -> `toexponential`

- package.json
Adds the manifests to the export map so they can be accessed by tools that utilize Node's module resolution. For example, if you tried to run this:
```js
import nativeReplacements from 'module-replacements/manifests/native.json' with { type: 'json' };
console.log(nativeReplacements);
```
You'd see this:
```
node:internal/modules/esm/resolve:299
return new ERR_PACKAGE_PATH_NOT_EXPORTED(
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './manifests/native.json' is not defined by "exports" in /home/ryun/Projects/deptree/node_modules/module-replacements/package.json imported from /home/ryun/Projects/deptree/index.js
```
Also adds `package.json` to the exports map too -- it's a handy thing that many other libraries offer. Never know, someone might want to access it in a script for some …
> feat: Add manifests to exports map

- docs/modules/README.md
- docs/modules/md5.md
- manifests/native.json
- manifests/preferred.json
I noticed there were some discrepancies between the codemods we have, and the packages that are in module-replacements. I think the codemods should always follow what's in module-replacements, so here's a PR that adds the missing packages. Once this is merged and released I'll add a script in the codemods repo that checks on PR to see if the contributed codemod is actually in module-replacements or not to avoid discrepancies in the future.
> feat: add missing packages

- manifests/micro-utilities.json
- manifests/native.json
- manifests/preferred.json
- package.json
- scripts/check-manifest-problems.js
- scripts/sort-manifests.js
- scripts/update-manifests-dist-path.js
- scripts/validate-manifests.js
- scripts/validate-module-list.js
- scripts/validate-modules.js
Adds some scripts to check the following:
- Module lists are sorted a-z
- No manifest contains duplicate modules
Also adds a script for sorting the module lists and writing the files back to disk.
> chore: add manifest validate scripts

- docs/modules/README.md
- docs/modules/ora.md
- manifests/preferred.json
Closes #144 
This pull request adds `ora` as a list of dependencies that can be replaced with smaller alternatives. The alternatives considered are:
1. [`nanospinner`](https://github.com/usmanyunusov/nanospinner)
2. [`tiny-spinner`](https://github.com/fabiospampinato/tiny-spinner)
> feat: add ora alternatives

- docs/modules/README.md
- manifests/preferred.json
Closes #141 
This pull request registers `ezspawn` and `@jsdevtools/ez-spawn` as replaceable process execution libraries.
> docs: register ezspawn and @jsdevtools/ez-spawn as process exec libraries

- docs/modules/README.md
- docs/modules/eslint-plugin-vitest.md
- docs/modules/faker.md
- docs/modules/xmldom.md
- manifests/preferred.json
Closes https://github.com/es-tooling/module-replacements/issues/167
This pull request adds alternative replacements for [faker](https://www.npmjs.com/package/faker), [xmldom](https://www.npmjs.com/package/xmldom) and [eslint-plugin-vitest](https://www.npmjs.com/package/eslint-plugin-vitest).
> docs: Add faker, xmldom and eslint-plugin-vitest

- docs/modules/README.md
- docs/modules/fs-extra.md
- docs/templates/module.md
- manifests/preferred.json
Closes (#126)
Snippets to add:
> Feat: Add `fs-extra`

- docs/modules/ora.md
Adds `picospinner` to the list of alternatives for `ora`.
> docs: add picospinner to ora docs

- docs/modules/dotenv.md
This relatively new nodejs flag is even closer in behavior to `import 'dotenv/config'`, since node will not refuse to start if the env-file does not exist.
Ref #152
> Mention nodejs `--env-file-if-exists` in dotenv alternatives

- docs/modules/README.md
- docs/modules/buf-compare.md
- manifests/preferred.json
> add `buf-compare` replacement

- docs/modules/README.md
- docs/modules/chalk.md
- manifests/preferred.json
Adds `chalk` and `cli-color` to the preferred manifest and documents alternatives.
Closes #149
> docs: add chalk to preferred manifest

- docs/modules/README.md
- docs/modules/js-yaml.md
- manifests/preferred.json
This recommends `yaml` over `js-yaml`.
Closes #197
> Add js-yaml

- docs/modules/README.md
- docs/modules/axios.md
- manifests/preferred.json
Hi there 👋 
This PR adds documentation for `axios` alternatives to help developers reduce dependencies by using native solutions or lightweight libraries.
What's included:
- Native fetch API: The primary recommendation, now available in Node.js 18+ and all modern browsers
- ky: Tiny HTTP client based on fetch with a convenient API
- ofetch: Enhanced fetch with automatic parsing and interceptors
Key benefits:
- Reduce bundle size by eliminating axios dependency (axios is ~13KB minified + gzipped)
- Use native browser/Node.js APIs when possible
> docs: added `axios`

- docs/modules/README.md
- docs/modules/core-util-is.md
- manifests/preferred.json
> feat: add `core-util-is` to the preferred manifest
