es-tooling/module-replacements

- docs/modules/README.md
- docs/modules/eslint-plugin-import.md
- docs/modules/eslint-plugin-react.md
Adds docs for replacements of `eslint-plugin-import` and `eslint-plugin-react`.
> feat: add eslint plugins (import, react)

- .gitignore
- docs/modules/README.md
- docs/modules/materialize-css.md
- docs/modules/momentjs.md
Related: https://github.com/es-tooling/module-replacements/issues/14
> feat: add materialize-css

- .github/workflows/main.yml
This should allow CI to run on the main branch again
> Fix branch name in CI

- docs/modules/README.md
- docs/modules/bluebird.md
- manifests/native.json
- manifests/preferred.json
as requested in https://github.com/es-tooling/module-replacements/pull/28
> chore: move bluebird from native to preferred

- manifests/native.json
> Add some too bloated `Object` polyfills

- manifests/native.json
> Add some too bloated `Number` polyfills

- manifests/native.json
> Add some too bloated `Math` polyfills

- docs/modules/sort-object.md
- manifests/preferred.json
resolves https://github.com/es-tooling/module-replacements/issues/59
Recommends 3 APIs:
1. Vanilla JS
2. [`sort-object-keys`](https://www.npmjs.com/package/sort-object-keys)
3. [`sortobject`](https://www.npmjs.com/package/sortobject)
> feat: Add `sort-object` replacement

- manifests/native.json
Resume #39.
Without adding polyfills for recent features.
> Add some too bloated `Promise` polyfills

- manifests/micro-utilities.json
Implements suggestions from #108
> refactor: Update replacement suggestion for `is-plain-object`

- manifests/native.json
Closes #112
This package is not on npm - https://www.npmjs.com/package/math.sinh
> Remove `math.sinh`

- README.md
- docs/modules/bluebird-q.md
- docs/modules/cpx.md
- docs/modules/eslint-plugin-es.md
- docs/modules/eslint-plugin-eslint-comments.md
- docs/modules/eslint-plugin-import.md
- docs/modules/eslint-plugin-node.md
- docs/modules/eslint-plugin-react.md
- docs/modules/materialize-css.md
- docs/modules/momentjs.md
- docs/modules/npm-run-all.md
- docs/templates/module.md
https://github.com/npm/cli#is-it-npm-or-npm-or-npm
> docs: use correct npm capitalization

- docs/modules/qs.md
> feat: add `neoqs`

- docs/modules/qs.md
> fix: `qs` inconsistent documentation

- docs/modules/README.md
- docs/modules/path-exists.md
- manifests/preferred.json
#156 
https://nodejs.org/docs/latest/api/fs.html#fsexistssyncpath
> feat: add `path-exists` in documentation

- docs/modules/README.md
- docs/modules/strip-ansi.md
- manifests/preferred.json
Closes #164
This pull request adds alternative replacements for [`strip-ansi`](https://www.npmjs.com/package/strip-ansi) package as discussed from the Discord channel.
> docs: add strip-ansi

- docs/modules/README.md
- docs/modules/dotenv.md
- manifests/preferred.json
> docs: add dotenv alternatives

- docs/modules/README.md
- docs/modules/buffer-equal.md
- manifests/preferred.json
Closes #170 
Please double-check this looks good, thanks!
> Add `buffer-equal` replacement

- docs/modules/README.md
- docs/modules/grapheme.md
- manifests/native.json
- manifests/preferred.json
Discussed in https://github.com/es-tooling/ecosystem-cleanup/issues/70
> feat: add `grapheme-splitter` and `grapheme` alternatives

- docs/modules/README.md
- docs/modules/lint-staged.md
- manifests/preferred.json
Closes #169 
This pull request adds `lint-staged` section and its replacement, `nano-staged`.
> docs: add lint-staged

- docs/modules/rimraf.md
context:
https://github.com/e18e/ecosystem-issues/issues/178#issuecomment-2976034507
https://github.com/e18e/e18e/pull/80
> docs(rimraf): document `fs.rm` maxRetries on Windows
